### ISSUE TITLE
version solving failed.

### ISSUE THREAD

**Issue by achinverma** [marchdev-tk/flutter_google_maps#76]
HI, i am trying to add this lib into my project but i am getting this below error, Pls see and guide me.

```
Because image_picker >=0.8.2 depends on image_picker_platform_interface ^2.2.0 and no versions of image_picker_platform_interface match >2.2.0 <3.0.0, image_picker >=0.8.2 requires image_picker_platform_interface 2.2.0.
And because image_picker_platform_interface 2.2.0 depends on http ^0.13.0 and flutter_google_maps >=3.8.0 depends on http ^0.12.1, image_picker >=0.8.2 is incompatible with flutter_google_maps >=3.8.0.
So, because marketplace_service_provider depends on both flutter_google_maps ^4.0.0 and image_picker ^0.8.3+1, version solving failed.
pub get failed (1; So, because marketplace_service_provider depends on both flutter_google_maps ^4.0.0 and image_picker ^0.8.3+1, version solving failed.)
```

yaml file:
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  connectivity: ^3.0.6        #ANDROID IOS MACOS WEB
  shared_preferences: ^2.0.6  #ANDROID IOS LINUX MACOS WEB WINDOWS
  package_info_plus: ^1.0.4   #ANDROID IOS LINUX MACOS WEB WINDOWS
  device_info_plus: ^2.1.0    #ANDROID IOS LINUX MACOS WEB WINDOWS
  fluttertoast: ^8.0.8        #ANDROID IOS WEB
  get_it: ^7.1.3             #ANDROID IOS LINUX MACOS WEB WINDOWS
  rxdart: ^0.27.1            #ANDROID IOS LINUX MACOS WEB WINDOWS
  flutter_overlay_loader: ^0.1.1 #ANDROID IOS LINUX MACOS WEB WINDOWS
  badges: ^2.0.1                 #ANDROID IOS LINUX MACOS WEB WINDOWS
  html: ^0.15.0                 #ANDROID IOS LINUX MACOS WEB WINDOWS
  flutter_inner_drawer: ^1.0.0+1 #ANDROID IOS LINUX MACOS WEB WINDOWS
  smooth_page_indicator: ^0.2.3  #ANDROID IOS LINUX MACOS WEB WINDOWS
  url_launcher: ^6.0.9            #ANDROID IOS LINUX MACOS WEB WINDOWS
  whatsapp_unilink: ^2.0.0        #ANDROID IOS LINUX MACOS WEB WINDOWS
  pull_to_refresh: ^2.0.0         #ANDROID IOS LINUX MACOS WEB WINDOWS
  flutter_google_maps: ^4.0.0
  image_picker: ^0.8.3+1     #ANDROID IOS WEB
  intl: ^0.17.0              #ANDROID IOS LINUX MACOS WEB WINDOWS
  dotted_border: ^2.0.0      #ANDROID IOS LINUX MACOS WEB WINDOWS
  #google_maps_flutter: ^2.0.6 #ANDROID IOS
  event_bus: ^2.0.0          #ANDROID IOS LINUX MACOS WEB WINDOWS
  location: ^4.3.0           #ANDROID IOS MACOS WEB
  #flutter_html: ^2.0.0     #ANDROID IOS
  #firebase_messaging: ^10.0.4  #ANDROID IOS MACOS WEB
  flutter_local_notifications: ^8.1.1+1   #ANDROID IOS MACOS
  #firebase_core: ^1.4.0                   #ANDROID IOS MACOS WEB
  flutter_native_timezone: ^2.0.0          #ANDROID IOS MACOS WEB
  expandable: ^5.0.1         #ANDROID IOS MACOS WEB
  share_plus: ^2.1.4            #ANDROID IOS MACOS WEB
  video_player: ^2.1.14         #ANDROID IOS WEB
  universal_html: ^2.0.8          #ANDROID IOS WEB
  latlng: ^0.1.0                   #ANDROID IOS WEB
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
```
